version: '3.5'

services:
  sistema-cnj-jus-br:
    image: ${DOCKER_REGISTRY}dsa/sistema.cnj.jus.br:${BRANCH}.${VERSION}-publish
    build:
      target: release
      args:
        VERSION: ${VERSION}
        BRANCH: ${BRANCH}
    volumes:
      - app:/var/release/

volumes:
  app:
    name: ${DOCKERCOMPOSE_PUBLISH_VOLUME_NAME:-app-extract-app}
