version: '3.6'

services:
  app-front-end:
    image: ${DOCKER_REGISTRY}dsa/sistema.cnj.jus.br:${BRANCH}.${VERSION}-publish
    container_name: sistema.cnj.jus.br-${BRANCH}-publish
    build:
      target: release
      args:
        VERSION: ${VERSION}
        BRANCH: ${BRANCH}
    volumes:
      - app:/var/release/

volumes:
  app:
    name: ${DOCKERCOMPOSE_PUBLISH_VOLUME_NAME:-app-extract-app}

networks:
  default:
    name: ns-sistema-${BRANCH}-${VERSION}-publish
