version: '3.6'

services:
  app-front-end:
    image: ${DOCKER_REGISTRY}dsa/sistema.tjmt.jus.br:${BRANCH:-develop}.${VERSION:-local}-ci
    container_name: sistema.tjmt.jus.br-ci
    build:
      target: ci
    environment:
      RUN_TEST: ${RUN_TEST:-true}
      RUN_PROJECT: ${RUN_PROJECT:-false}
      RUN_SONARQUBE: ${RUN_SONARQUBE:-true}
      SONARQUBE_URL: ${SONARQUBE_URL:-http://172.17.0.1:9000}
      SONARQUBE_LOGIN: ${SONARQUBE_LOGIN}
      SONARQUBE_PROJECT: sistema.cnj.jus.br
      SONARQUBE_PROJECT_VERSION: ${VERSION:-local}
    volumes:
      - test-result:/TestResults

volumes:
  test-result:
    name: ${DOCKERCOMPOSE_CI_VOLUME_NAME:-app-test-results}

networks:
  default:
    name: ns-sistema-${BRANCH}-${VERSION}-ci    